ls:
  .dir: regex:\.?[a-z0-9]+(-[a-z0-9]+)*
  .yaml: regex:[a-z0-9]*([._][a-z0-9]+)* | regex:pnpm-(lock|workspace)
  .*: regex:[a-z0-9]*([._][a-z0-9]+)*

ignore:
  - .git
  - .direnv
  - result
  - result-*
  - docs/logs

  - README.md
  - Cargo.toml
  - Cargo.lock

  - target
  - node_modules
  - .pnpm-store
